[project]
name = "omni-contract"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.cross-chain]
path = "contracts/cross-chain.clar"
depends_on = []

[contracts.dynamic-discounting]
path = "contracts/dynamic-discounting.clar"
depends_on = []

[contracts.swap-aggregator]
path = "contracts/swap-aggregator.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
